// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs45c252fa8rWuD_lGZS6K-mBhFqZgKCg',
    appId: '1:120681281186:web:4bb577951d6970a8f2c9fb',
    messagingSenderId: '120681281186',
    projectId: 'lovable-8e28b',
    authDomain: 'lovable-8e28b.firebaseapp.com',
    storageBucket: 'lovable-8e28b.firebasestorage.app',
    measurementId: 'G-NQFX1B955L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8gPbK-kEnUqDFMwOSvH1i7DuBGCQlBhw',
    appId: '1:120681281186:android:92462ae537d34ba7f2c9fb',
    messagingSenderId: '120681281186',
    projectId: 'lovable-8e28b',
    storageBucket: 'lovable-8e28b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLIYdjzRz5UYKtRD_M7Pt8AOV2jjqssWs',
    appId: '1:120681281186:ios:3643062638982379f2c9fb',
    messagingSenderId: '120681281186',
    projectId: 'lovable-8e28b',
    storageBucket: 'lovable-8e28b.firebasestorage.app',
    iosBundleId: 'com.example.lovely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLIYdjzRz5UYKtRD_M7Pt8AOV2jjqssWs',
    appId: '1:120681281186:ios:3643062638982379f2c9fb',
    messagingSenderId: '120681281186',
    projectId: 'lovable-8e28b',
    storageBucket: 'lovable-8e28b.firebasestorage.app',
    iosBundleId: 'com.example.lovely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs45c252fa8rWuD_lGZS6K-mBhFqZgKCg',
    appId: '1:120681281186:web:f9637a3aad5a9c95f2c9fb',
    messagingSenderId: '120681281186',
    projectId: 'lovable-8e28b',
    authDomain: 'lovable-8e28b.firebaseapp.com',
    storageBucket: 'lovable-8e28b.firebasestorage.app',
    measurementId: 'G-TY0BKYQWRP',
  );

}
